version: "3.9"
services:
  postgres:
    image: postgres:14.5
    container_name: pg1
    volumes:
      - /data/pg/db:/var/lib/postgresql/data
      - /data/pg/backup:/backup
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
